/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class BlobGroup extends FeatureVector {
  private long swigCPtr;

  protected BlobGroup(long cPtr, boolean cMemoryOwn) {
    super(libtischJNI.SWIGBlobGroupUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BlobGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_BlobGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BlobGroup(long tf) {
    this(libtischJNI.new_BlobGroup__SWIG_0(tf), true);
  }

  public BlobGroup() {
    this(libtischJNI.new_BlobGroup__SWIG_1(), true);
  }

  public FeatureBase clone() {
    long cPtr = libtischJNI.BlobGroup_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new BlobGroup(cPtr, false);
  }

  public void load(InputState state) {
    libtischJNI.BlobGroup_load(swigCPtr, this, InputState.getCPtr(state), state);
  }

  public int next() {
    return libtischJNI.BlobGroup_next(swigCPtr, this);
  }

  public String name() {
    return libtischJNI.BlobGroup_name(swigCPtr, this);
  }

  public static BlobGroup dynamic_cast(FeatureBase base) {
    long cPtr = libtischJNI.BlobGroup_dynamic_cast(FeatureBase.getCPtr(base), base);
    return (cPtr == 0) ? null : new BlobGroup(cPtr, false);
  }

}
