/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class BlobCount extends FeatureInt {
  private long swigCPtr;

  protected BlobCount(long cPtr, boolean cMemoryOwn) {
    super(libtischJNI.SWIGBlobCountUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BlobCount obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_BlobCount(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BlobCount(long tf) {
    this(libtischJNI.new_BlobCount__SWIG_0(tf), true);
  }

  public BlobCount() {
    this(libtischJNI.new_BlobCount__SWIG_1(), true);
  }

  public FeatureBase clone() {
    long cPtr = libtischJNI.BlobCount_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new BlobCount(cPtr, false);
  }

  public void load(InputState state) {
    libtischJNI.BlobCount_load(swigCPtr, this, InputState.getCPtr(state), state);
  }

  public String name() {
    return libtischJNI.BlobCount_name(swigCPtr, this);
  }

  public static BlobCount dynamic_cast(FeatureBase base) {
    long cPtr = libtischJNI.BlobCount_dynamic_cast(FeatureBase.getCPtr(base), base);
    return (cPtr == 0) ? null : new BlobCount(cPtr, false);
  }

}
