/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class Button extends Widget {
  private long swigCPtr;

  protected Button(long cPtr, boolean cMemoryOwn) {
    super(libtischJNI.SWIGButtonUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Button obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_Button(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    libtischJNI.Button_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    libtischJNI.Button_change_ownership(this, swigCPtr, true);
  }

  public Button(int _w, int _h, int _x, int _y, double angle, RGBATexture _tex) {
    this(libtischJNI.new_Button__SWIG_0(_w, _h, _x, _y, angle, libtischJNI.getCPtrAddRef(_tex), _tex), true);
    libtischJNI.Button_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public Button(int _w, int _h, int _x, int _y, double angle) {
    this(libtischJNI.new_Button__SWIG_1(_w, _h, _x, _y, angle), true);
    libtischJNI.Button_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public Button(int _w, int _h, int _x, int _y) {
    this(libtischJNI.new_Button__SWIG_2(_w, _h, _x, _y), true);
    libtischJNI.Button_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public Button(int _w, int _h, int _x) {
    this(libtischJNI.new_Button__SWIG_3(_w, _h, _x), true);
    libtischJNI.Button_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public Button(int _w, int _h) {
    this(libtischJNI.new_Button__SWIG_4(_w, _h), true);
    libtischJNI.Button_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void draw() {
    if (getClass() == Button.class) libtischJNI.Button_draw(swigCPtr, this); else libtischJNI.Button_drawSwigExplicitButton(swigCPtr, this);
  }

  public void action(Gesture gesture) {
    if (getClass() == Button.class) libtischJNI.Button_action(swigCPtr, this, Gesture.getCPtr(gesture), gesture); else libtischJNI.Button_actionSwigExplicitButton(swigCPtr, this, Gesture.getCPtr(gesture), gesture);
  }

  public void tap(Vector pos, int id) {
    if (getClass() == Button.class) libtischJNI.Button_tap(swigCPtr, this, Vector.getCPtr(pos), pos, id); else libtischJNI.Button_tapSwigExplicitButton(swigCPtr, this, Vector.getCPtr(pos), pos, id);
  }

  public void release() {
    if (getClass() == Button.class) libtischJNI.Button_release(swigCPtr, this); else libtischJNI.Button_releaseSwigExplicitButton(swigCPtr, this);
  }

  protected void setActive(int value) {
    libtischJNI.Button_active_set(swigCPtr, this, value);
  }

  protected int getActive() {
    return libtischJNI.Button_active_get(swigCPtr, this);
  }

}
