/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class Dimensions {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Dimensions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Dimensions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_Dimensions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX1(double value) {
    libtischJNI.Dimensions_x1_set(swigCPtr, this, value);
  }

  public double getX1() {
    return libtischJNI.Dimensions_x1_get(swigCPtr, this);
  }

  public void setY1(double value) {
    libtischJNI.Dimensions_y1_set(swigCPtr, this, value);
  }

  public double getY1() {
    return libtischJNI.Dimensions_y1_get(swigCPtr, this);
  }

  public void setX2(double value) {
    libtischJNI.Dimensions_x2_set(swigCPtr, this, value);
  }

  public double getX2() {
    return libtischJNI.Dimensions_x2_get(swigCPtr, this);
  }

  public void setY2(double value) {
    libtischJNI.Dimensions_y2_set(swigCPtr, this, value);
  }

  public double getY2() {
    return libtischJNI.Dimensions_y2_get(swigCPtr, this);
  }

  public void setSize(double value) {
    libtischJNI.Dimensions_size_set(swigCPtr, this, value);
  }

  public double getSize() {
    return libtischJNI.Dimensions_size_get(swigCPtr, this);
  }

  public Dimensions() {
    this(libtischJNI.new_Dimensions(), true);
  }

}
