/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class InputState extends vectorBlobState {
  private long swigCPtr;

  protected InputState(long cPtr, boolean cMemoryOwn) {
    super(libtischJNI.SWIGInputStateUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InputState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_InputState(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public InputState() {
    this(libtischJNI.new_InputState(), true);
  }

  public void purge() {
    libtischJNI.InputState_purge(swigCPtr, this);
  }

  public int changed() {
    return libtischJNI.InputState_changed(swigCPtr, this);
  }

}
