/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class InternalMatcher extends Matcher {
  private long swigCPtr;

  protected InternalMatcher(long cPtr, boolean cMemoryOwn) {
    super(libtischJNI.SWIGInternalMatcherUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InternalMatcher obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_InternalMatcher(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public InternalMatcher() {
    this(libtischJNI.new_InternalMatcher(), true);
  }

  public void process_gestures() {
    libtischJNI.InternalMatcher_process_gestures(swigCPtr, this);
  }

  public int do_process_gestures() {
    return libtischJNI.InternalMatcher_do_process_gestures(swigCPtr, this);
  }

  public void request_update(int id) {
    libtischJNI.InternalMatcher_request_update(swigCPtr, this, id);
  }

  public void trigger_gesture(int id, Gesture g) {
    libtischJNI.InternalMatcher_trigger_gesture(swigCPtr, this, id, Gesture.getCPtr(g), g);
  }

}
