/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class IntVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IntVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_IntVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntVector(int _x, int _y, int _z) {
    this(libtischJNI.new_IntVector__SWIG_0(_x, _y, _z), true);
  }

  public IntVector(int _x, int _y) {
    this(libtischJNI.new_IntVector__SWIG_1(_x, _y), true);
  }

  public IntVector(int _x) {
    this(libtischJNI.new_IntVector__SWIG_2(_x), true);
  }

  public IntVector() {
    this(libtischJNI.new_IntVector__SWIG_3(), true);
  }

  public void normalize() {
    libtischJNI.IntVector_normalize(swigCPtr, this);
  }

  public void set(int _x, int _y, int _z) {
    libtischJNI.IntVector_set__SWIG_0(swigCPtr, this, _x, _y, _z);
  }

  public void set(int _x, int _y) {
    libtischJNI.IntVector_set__SWIG_1(swigCPtr, this, _x, _y);
  }

  public void set(int _x) {
    libtischJNI.IntVector_set__SWIG_2(swigCPtr, this, _x);
  }

  public void set() {
    libtischJNI.IntVector_set__SWIG_3(swigCPtr, this);
  }

  public double length() {
    return libtischJNI.IntVector_length(swigCPtr, this);
  }

  public void rotate(double angle) {
    libtischJNI.IntVector_rotate(swigCPtr, this, angle);
  }

  public IntVector round() {
    return new IntVector(libtischJNI.IntVector_round(swigCPtr, this), true);
  }

  public void setX(int value) {
    libtischJNI.IntVector_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return libtischJNI.IntVector_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    libtischJNI.IntVector_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return libtischJNI.IntVector_y_get(swigCPtr, this);
  }

  public void setZ(int value) {
    libtischJNI.IntVector_z_set(swigCPtr, this, value);
  }

  public int getZ() {
    return libtischJNI.IntVector_z_get(swigCPtr, this);
  }

}
