/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class mapIntBlobHistory {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected mapIntBlobHistory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(mapIntBlobHistory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_mapIntBlobHistory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public mapIntBlobHistory() {
    this(libtischJNI.new_mapIntBlobHistory__SWIG_0(), true);
  }

  public mapIntBlobHistory(mapIntBlobHistory arg0) {
    this(libtischJNI.new_mapIntBlobHistory__SWIG_1(mapIntBlobHistory.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return libtischJNI.mapIntBlobHistory_size(swigCPtr, this);
  }

  public boolean empty() {
    return libtischJNI.mapIntBlobHistory_empty(swigCPtr, this);
  }

  public void clear() {
    libtischJNI.mapIntBlobHistory_clear(swigCPtr, this);
  }

  public BlobHistory get(int key) {
    return new BlobHistory(libtischJNI.mapIntBlobHistory_get(swigCPtr, this, key), false);
  }

  public void set(int key, BlobHistory x) {
    libtischJNI.mapIntBlobHistory_set(swigCPtr, this, key, BlobHistory.getCPtr(x), x);
  }

  public void del(int key) {
    libtischJNI.mapIntBlobHistory_del(swigCPtr, this, key);
  }

  public boolean has_key(int key) {
    return libtischJNI.mapIntBlobHistory_has_key(swigCPtr, this, key);
  }

}
