/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class Rotation extends FeatureDouble {
  private long swigCPtr;

  protected Rotation(long cPtr, boolean cMemoryOwn) {
    super(libtischJNI.SWIGRotationUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Rotation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_Rotation(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Rotation(long tf) {
    this(libtischJNI.new_Rotation__SWIG_0(tf), true);
  }

  public Rotation() {
    this(libtischJNI.new_Rotation__SWIG_1(), true);
  }

  public FeatureBase clone() {
    long cPtr = libtischJNI.Rotation_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Rotation(cPtr, false);
  }

  public void load(InputState state) {
    libtischJNI.Rotation_load(swigCPtr, this, InputState.getCPtr(state), state);
  }

  public String name() {
    return libtischJNI.Rotation_name(swigCPtr, this);
  }

  public static Rotation dynamic_cast(FeatureBase base) {
    long cPtr = libtischJNI.Rotation_dynamic_cast(FeatureBase.getCPtr(base), base);
    return (cPtr == 0) ? null : new Rotation(cPtr, false);
  }

}
