/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class Scale extends FeatureDouble {
  private long swigCPtr;

  protected Scale(long cPtr, boolean cMemoryOwn) {
    super(libtischJNI.SWIGScaleUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Scale obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_Scale(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Scale(long tf) {
    this(libtischJNI.new_Scale__SWIG_0(tf), true);
  }

  public Scale() {
    this(libtischJNI.new_Scale__SWIG_1(), true);
  }

  public FeatureBase clone() {
    long cPtr = libtischJNI.Scale_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Scale(cPtr, false);
  }

  public void load(InputState state) {
    libtischJNI.Scale_load(swigCPtr, this, InputState.getCPtr(state), state);
  }

  public String name() {
    return libtischJNI.Scale_name(swigCPtr, this);
  }

  public static Scale dynamic_cast(FeatureBase base) {
    long cPtr = libtischJNI.Scale_dynamic_cast(FeatureBase.getCPtr(base), base);
    return (cPtr == 0) ? null : new Scale(cPtr, false);
  }

}
