/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class Slider extends Widget {
  private long swigCPtr;

  protected Slider(long cPtr, boolean cMemoryOwn) {
    super(libtischJNI.SWIGSliderUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Slider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_Slider(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    libtischJNI.Slider_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    libtischJNI.Slider_change_ownership(this, swigCPtr, true);
  }

  public Slider(int _w, int _h, int _x, int _y, double angle, RGBATexture _tex) {
    this(libtischJNI.new_Slider__SWIG_0(_w, _h, _x, _y, angle, libtischJNI.getCPtrAddRef(_tex), _tex), true);
    libtischJNI.Slider_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public Slider(int _w, int _h, int _x, int _y, double angle) {
    this(libtischJNI.new_Slider__SWIG_1(_w, _h, _x, _y, angle), true);
    libtischJNI.Slider_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public Slider(int _w, int _h, int _x, int _y) {
    this(libtischJNI.new_Slider__SWIG_2(_w, _h, _x, _y), true);
    libtischJNI.Slider_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public Slider(int _w, int _h, int _x) {
    this(libtischJNI.new_Slider__SWIG_3(_w, _h, _x), true);
    libtischJNI.Slider_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public Slider(int _w, int _h) {
    this(libtischJNI.new_Slider__SWIG_4(_w, _h), true);
    libtischJNI.Slider_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void action(Gesture gesture) {
    if (getClass() == Slider.class) libtischJNI.Slider_action(swigCPtr, this, Gesture.getCPtr(gesture), gesture); else libtischJNI.Slider_actionSwigExplicitSlider(swigCPtr, this, Gesture.getCPtr(gesture), gesture);
  }

  public void draw() {
    if (getClass() == Slider.class) libtischJNI.Slider_draw(swigCPtr, this); else libtischJNI.Slider_drawSwigExplicitSlider(swigCPtr, this);
  }

  public double getpos() {
    return libtischJNI.Slider_getpos(swigCPtr, this);
  }

  protected void setPos(double value) {
    libtischJNI.Slider_pos_set(swigCPtr, this, value);
  }

  protected double getPos() {
    return libtischJNI.Slider_pos_get(swigCPtr, this);
  }

}
