/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class smartPtrFeatureBase {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected smartPtrFeatureBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(smartPtrFeatureBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_smartPtrFeatureBase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public smartPtrFeatureBase(FeatureBase p) {
    this(libtischJNI.new_smartPtrFeatureBase__SWIG_0(FeatureBase.getCPtr(p), p), true);
  }

  public smartPtrFeatureBase() {
    this(libtischJNI.new_smartPtrFeatureBase__SWIG_1(), true);
  }

  public smartPtrFeatureBase(smartPtrFeatureBase r) {
    this(libtischJNI.new_smartPtrFeatureBase__SWIG_2(smartPtrFeatureBase.getCPtr(r), r), true);
  }

  public smartPtrFeatureBase assign(smartPtrFeatureBase r) {
    return new smartPtrFeatureBase(libtischJNI.smartPtrFeatureBase_assign(swigCPtr, this, smartPtrFeatureBase.getCPtr(r), r), false);
  }

  public FeatureBase __ref__() {
    return new FeatureBase(libtischJNI.smartPtrFeatureBase___ref__(swigCPtr, this), false);
  }

  public FeatureBase __deref__() {
    long cPtr = libtischJNI.smartPtrFeatureBase___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureBase(cPtr, false);
  }

  public FeatureBase get() {
    long cPtr = libtischJNI.smartPtrFeatureBase_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureBase(cPtr, false);
  }

  public boolean unique() {
    return libtischJNI.smartPtrFeatureBase_unique(swigCPtr, this);
  }

  public String name() {
    return libtischJNI.smartPtrFeatureBase_name(swigCPtr, this);
  }

  public FeatureBase clone() {
    long cPtr = libtischJNI.smartPtrFeatureBase_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureBase(cPtr, false);
  }

  public void load(InputState state) {
    libtischJNI.smartPtrFeatureBase_load(swigCPtr, this, InputState.getCPtr(state), state);
  }

  public int next() {
    return libtischJNI.smartPtrFeatureBase_next(swigCPtr, this);
  }

  public void serialize(SWIGTYPE_p_std__ostream s) {
    libtischJNI.smartPtrFeatureBase_serialize(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(s));
  }

  public void unserialize(SWIGTYPE_p_std__istream s) {
    libtischJNI.smartPtrFeatureBase_unserialize(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(s));
  }

  public void setHas_result(int value) {
    libtischJNI.smartPtrFeatureBase_has_result_set(swigCPtr, this, value);
  }

  public int getHas_result() {
    return libtischJNI.smartPtrFeatureBase_has_result_get(swigCPtr, this);
  }

}
