/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class Textbox extends Widget {
  private long swigCPtr;

  protected Textbox(long cPtr, boolean cMemoryOwn) {
    super(libtischJNI.SWIGTextboxUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Textbox obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_Textbox(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Textbox(int _w, int _h0, int _h1, int _x, int _y, double angle, RGBATexture _tex) {
    this(libtischJNI.new_Textbox__SWIG_0(_w, _h0, _h1, _x, _y, angle, libtischJNI.getCPtrAddRef(_tex), _tex), true);
  }

  public Textbox(int _w, int _h0, int _h1, int _x, int _y, double angle) {
    this(libtischJNI.new_Textbox__SWIG_1(_w, _h0, _h1, _x, _y, angle), true);
  }

  public Textbox(int _w, int _h0, int _h1, int _x, int _y) {
    this(libtischJNI.new_Textbox__SWIG_2(_w, _h0, _h1, _x, _y), true);
  }

  public Textbox(int _w, int _h0, int _h1, int _x) {
    this(libtischJNI.new_Textbox__SWIG_3(_w, _h0, _h1, _x), true);
  }

  public Textbox(int _w, int _h0, int _h1) {
    this(libtischJNI.new_Textbox__SWIG_4(_w, _h0, _h1), true);
  }

  public void draw() {
    libtischJNI.Textbox_draw(swigCPtr, this);
  }

  public void action(Gesture gesture) {
    libtischJNI.Textbox_action(swigCPtr, this, Gesture.getCPtr(gesture), gesture);
  }

  public String get() {
    return libtischJNI.Textbox_get(swigCPtr, this);
  }

  public void set(String _text) {
    libtischJNI.Textbox_set(swigCPtr, this, _text);
  }

}
