/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class vectorSmartPtrFeatureBase {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vectorSmartPtrFeatureBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorSmartPtrFeatureBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_vectorSmartPtrFeatureBase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorSmartPtrFeatureBase() {
    this(libtischJNI.new_vectorSmartPtrFeatureBase__SWIG_0(), true);
  }

  public vectorSmartPtrFeatureBase(long n) {
    this(libtischJNI.new_vectorSmartPtrFeatureBase__SWIG_1(n), true);
  }

  public long size() {
    return libtischJNI.vectorSmartPtrFeatureBase_size(swigCPtr, this);
  }

  public long capacity() {
    return libtischJNI.vectorSmartPtrFeatureBase_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libtischJNI.vectorSmartPtrFeatureBase_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libtischJNI.vectorSmartPtrFeatureBase_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libtischJNI.vectorSmartPtrFeatureBase_clear(swigCPtr, this);
  }

  public void add(smartPtrFeatureBase x) {
    libtischJNI.vectorSmartPtrFeatureBase_add(swigCPtr, this, smartPtrFeatureBase.getCPtr(x), x);
  }

  public smartPtrFeatureBase get(int i) {
    return new smartPtrFeatureBase(libtischJNI.vectorSmartPtrFeatureBase_get(swigCPtr, this, i), false);
  }

  public void set(int i, smartPtrFeatureBase val) {
    libtischJNI.vectorSmartPtrFeatureBase_set(swigCPtr, this, i, smartPtrFeatureBase.getCPtr(val), val);
  }

}
