/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class vectorDouble {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vectorDouble(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_vectorDouble(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorDouble() {
    this(libtischJNI.new_vectorDouble__SWIG_0(), true);
  }

  public vectorDouble(long n) {
    this(libtischJNI.new_vectorDouble__SWIG_1(n), true);
  }

  public long size() {
    return libtischJNI.vectorDouble_size(swigCPtr, this);
  }

  public long capacity() {
    return libtischJNI.vectorDouble_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libtischJNI.vectorDouble_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libtischJNI.vectorDouble_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libtischJNI.vectorDouble_clear(swigCPtr, this);
  }

  public void add(double x) {
    libtischJNI.vectorDouble_add(swigCPtr, this, x);
  }

  public double get(int i) {
    return libtischJNI.vectorDouble_get(swigCPtr, this, i);
  }

  public void set(int i, double val) {
    libtischJNI.vectorDouble_set(swigCPtr, this, i, val);
  }

}
