/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class vectorBlobState {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vectorBlobState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorBlobState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtischJNI.delete_vectorBlobState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorBlobState() {
    this(libtischJNI.new_vectorBlobState__SWIG_0(), true);
  }

  public vectorBlobState(long n) {
    this(libtischJNI.new_vectorBlobState__SWIG_1(n), true);
  }

  public long size() {
    return libtischJNI.vectorBlobState_size(swigCPtr, this);
  }

  public long capacity() {
    return libtischJNI.vectorBlobState_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libtischJNI.vectorBlobState_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libtischJNI.vectorBlobState_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libtischJNI.vectorBlobState_clear(swigCPtr, this);
  }

  public void add(BlobState x) {
    libtischJNI.vectorBlobState_add(swigCPtr, this, BlobState.getCPtr(x), x);
  }

  public BlobState get(int i) {
    return new BlobState(libtischJNI.vectorBlobState_get(swigCPtr, this, i), false);
  }

  public void set(int i, BlobState val) {
    libtischJNI.vectorBlobState_set(swigCPtr, this, i, BlobState.getCPtr(val), val);
  }

}
