/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class Button : Widget {
  private HandleRef swigCPtr;

  internal Button(IntPtr cPtr, bool cMemoryOwn) : base(libtischPINVOKE.ButtonUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Button obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Button() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libtischPINVOKE.delete_Button(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public Button(int _w, int _h, int _x, int _y, double angle, RGBATexture _tex) : this(libtischPINVOKE.new_Button__SWIG_0(_w, _h, _x, _y, angle, libtischPINVOKE.getCPtrAddRef(_tex)), true) {
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  public Button(int _w, int _h, int _x, int _y, double angle) : this(libtischPINVOKE.new_Button__SWIG_1(_w, _h, _x, _y, angle), true) {
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  public Button(int _w, int _h, int _x, int _y) : this(libtischPINVOKE.new_Button__SWIG_2(_w, _h, _x, _y), true) {
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  public Button(int _w, int _h, int _x) : this(libtischPINVOKE.new_Button__SWIG_3(_w, _h, _x), true) {
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  public Button(int _w, int _h) : this(libtischPINVOKE.new_Button__SWIG_4(_w, _h), true) {
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  public override void draw() {
    if (this.GetType() == typeof(Button)) libtischPINVOKE.Button_draw(swigCPtr); else libtischPINVOKE.Button_drawSwigExplicitButton(swigCPtr);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void action(Gesture gesture) {
    if (this.GetType() == typeof(Button)) libtischPINVOKE.Button_action(swigCPtr, Gesture.getCPtr(gesture)); else libtischPINVOKE.Button_actionSwigExplicitButton(swigCPtr, Gesture.getCPtr(gesture));
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void tap(Vector pos, int id) {
    if (this.GetType() == typeof(Button)) libtischPINVOKE.Button_tap(swigCPtr, Vector.getCPtr(pos), id); else libtischPINVOKE.Button_tapSwigExplicitButton(swigCPtr, Vector.getCPtr(pos), id);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void release() {
    if (this.GetType() == typeof(Button)) libtischPINVOKE.Button_release(swigCPtr); else libtischPINVOKE.Button_releaseSwigExplicitButton(swigCPtr);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  protected int active {
    set {
      libtischPINVOKE.Button_active_set(swigCPtr, value);
      if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      int ret = libtischPINVOKE.Button_active_get(swigCPtr);
      if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("outline", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateButton_0(SwigDirectoroutline);
    if (SwigDerivedClassHasMethod("update", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateButton_1(SwigDirectorupdate__SWIG_0);
    if (SwigDerivedClassHasMethod("update", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateButton_2(SwigDirectorupdate__SWIG_1);
    if (SwigDerivedClassHasMethod("doUpdate", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateButton_3(SwigDirectordoUpdate__SWIG_0);
    if (SwigDerivedClassHasMethod("doUpdate", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateButton_4(SwigDirectordoUpdate__SWIG_1);
    if (SwigDerivedClassHasMethod("doUpdate", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateButton_5(SwigDirectordoUpdate__SWIG_2);
    if (SwigDerivedClassHasMethod("raise", swigMethodTypes6))
      swigDelegate6 = new SwigDelegateButton_6(SwigDirectorraise__SWIG_0);
    if (SwigDerivedClassHasMethod("raise", swigMethodTypes7))
      swigDelegate7 = new SwigDelegateButton_7(SwigDirectorraise__SWIG_1);
    if (SwigDerivedClassHasMethod("lower", swigMethodTypes8))
      swigDelegate8 = new SwigDelegateButton_8(SwigDirectorlower__SWIG_0);
    if (SwigDerivedClassHasMethod("lower", swigMethodTypes9))
      swigDelegate9 = new SwigDelegateButton_9(SwigDirectorlower__SWIG_1);
    if (SwigDerivedClassHasMethod("draw", swigMethodTypes10))
      swigDelegate10 = new SwigDelegateButton_10(SwigDirectordraw);
    if (SwigDerivedClassHasMethod("action", swigMethodTypes11))
      swigDelegate11 = new SwigDelegateButton_11(SwigDirectoraction);
    if (SwigDerivedClassHasMethod("enter", swigMethodTypes12))
      swigDelegate12 = new SwigDelegateButton_12(SwigDirectorenter__SWIG_0);
    if (SwigDerivedClassHasMethod("enter", swigMethodTypes13))
      swigDelegate13 = new SwigDelegateButton_13(SwigDirectorenter__SWIG_1);
    if (SwigDerivedClassHasMethod("paint", swigMethodTypes14))
      swigDelegate14 = new SwigDelegateButton_14(SwigDirectorpaint__SWIG_0);
    if (SwigDerivedClassHasMethod("paint", swigMethodTypes15))
      swigDelegate15 = new SwigDelegateButton_15(SwigDirectorpaint__SWIG_1);
    if (SwigDerivedClassHasMethod("tap", swigMethodTypes16))
      swigDelegate16 = new SwigDelegateButton_16(SwigDirectortap);
    if (SwigDerivedClassHasMethod("release", swigMethodTypes17))
      swigDelegate17 = new SwigDelegateButton_17(SwigDirectorrelease);
    libtischPINVOKE.Button_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6, swigDelegate7, swigDelegate8, swigDelegate9, swigDelegate10, swigDelegate11, swigDelegate12, swigDelegate13, swigDelegate14, swigDelegate15, swigDelegate16, swigDelegate17);
  }

  private bool SwigDerivedClassHasMethod(string methodName, Type[] methodTypes) {
    System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(Button));
    return hasDerivedMethod;
  }

  private void SwigDirectoroutline() {
    outline();
  }

  private void SwigDirectorupdate__SWIG_0(IntPtr target) {
    update((target == IntPtr.Zero) ? null : new Widget(target, false));
  }

  private void SwigDirectorupdate__SWIG_1() {
    update();
  }

  private void SwigDirectordoUpdate__SWIG_0(IntPtr target, IntPtr ost) {
    doUpdate((target == IntPtr.Zero) ? null : new Widget(target, false), (ost == IntPtr.Zero) ? null : new SWIGTYPE_p_std__ostream(ost, false));
  }

  private void SwigDirectordoUpdate__SWIG_1(IntPtr target) {
    doUpdate((target == IntPtr.Zero) ? null : new Widget(target, false));
  }

  private void SwigDirectordoUpdate__SWIG_2() {
    doUpdate();
  }

  private void SwigDirectorraise__SWIG_0(IntPtr widget) {
    raise((widget == IntPtr.Zero) ? null : new Widget(widget, false));
  }

  private void SwigDirectorraise__SWIG_1() {
    raise();
  }

  private void SwigDirectorlower__SWIG_0(IntPtr widget) {
    lower((widget == IntPtr.Zero) ? null : new Widget(widget, false));
  }

  private void SwigDirectorlower__SWIG_1() {
    lower();
  }

  private void SwigDirectordraw() {
    draw();
  }

  private void SwigDirectoraction(IntPtr gesture) {
    action((gesture == IntPtr.Zero) ? null : new Gesture(gesture, false));
  }

  private void SwigDirectorenter__SWIG_0(double z) {
    enter(z);
  }

  private void SwigDirectorenter__SWIG_1() {
    enter();
  }

  private void SwigDirectorpaint__SWIG_0(bool update_stencil) {
    paint(update_stencil);
  }

  private void SwigDirectorpaint__SWIG_1() {
    paint();
  }

  private void SwigDirectortap(IntPtr pos, int id) {
    tap(new Vector(pos, false), id);
  }

  private void SwigDirectorrelease() {
    release();
  }

  public delegate void SwigDelegateButton_0();
  public delegate void SwigDelegateButton_1(IntPtr target);
  public delegate void SwigDelegateButton_2();
  public delegate void SwigDelegateButton_3(IntPtr target, IntPtr ost);
  public delegate void SwigDelegateButton_4(IntPtr target);
  public delegate void SwigDelegateButton_5();
  public delegate void SwigDelegateButton_6(IntPtr widget);
  public delegate void SwigDelegateButton_7();
  public delegate void SwigDelegateButton_8(IntPtr widget);
  public delegate void SwigDelegateButton_9();
  public delegate void SwigDelegateButton_10();
  public delegate void SwigDelegateButton_11(IntPtr gesture);
  public delegate void SwigDelegateButton_12(double z);
  public delegate void SwigDelegateButton_13();
  public delegate void SwigDelegateButton_14(bool update_stencil);
  public delegate void SwigDelegateButton_15();
  public delegate void SwigDelegateButton_16(IntPtr pos, int id);
  public delegate void SwigDelegateButton_17();

  private SwigDelegateButton_0 swigDelegate0;
  private SwigDelegateButton_1 swigDelegate1;
  private SwigDelegateButton_2 swigDelegate2;
  private SwigDelegateButton_3 swigDelegate3;
  private SwigDelegateButton_4 swigDelegate4;
  private SwigDelegateButton_5 swigDelegate5;
  private SwigDelegateButton_6 swigDelegate6;
  private SwigDelegateButton_7 swigDelegate7;
  private SwigDelegateButton_8 swigDelegate8;
  private SwigDelegateButton_9 swigDelegate9;
  private SwigDelegateButton_10 swigDelegate10;
  private SwigDelegateButton_11 swigDelegate11;
  private SwigDelegateButton_12 swigDelegate12;
  private SwigDelegateButton_13 swigDelegate13;
  private SwigDelegateButton_14 swigDelegate14;
  private SwigDelegateButton_15 swigDelegate15;
  private SwigDelegateButton_16 swigDelegate16;
  private SwigDelegateButton_17 swigDelegate17;

  private static Type[] swigMethodTypes0 = new Type[] {  };
  private static Type[] swigMethodTypes1 = new Type[] { typeof(Widget) };
  private static Type[] swigMethodTypes2 = new Type[] {  };
  private static Type[] swigMethodTypes3 = new Type[] { typeof(Widget), typeof(SWIGTYPE_p_std__ostream) };
  private static Type[] swigMethodTypes4 = new Type[] { typeof(Widget) };
  private static Type[] swigMethodTypes5 = new Type[] {  };
  private static Type[] swigMethodTypes6 = new Type[] { typeof(Widget) };
  private static Type[] swigMethodTypes7 = new Type[] {  };
  private static Type[] swigMethodTypes8 = new Type[] { typeof(Widget) };
  private static Type[] swigMethodTypes9 = new Type[] {  };
  private static Type[] swigMethodTypes10 = new Type[] {  };
  private static Type[] swigMethodTypes11 = new Type[] { typeof(Gesture) };
  private static Type[] swigMethodTypes12 = new Type[] { typeof(double) };
  private static Type[] swigMethodTypes13 = new Type[] {  };
  private static Type[] swigMethodTypes14 = new Type[] { typeof(bool) };
  private static Type[] swigMethodTypes15 = new Type[] {  };
  private static Type[] swigMethodTypes16 = new Type[] { typeof(Vector), typeof(int) };
  private static Type[] swigMethodTypes17 = new Type[] {  };
}
