/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class Dial : Widget {
  private HandleRef swigCPtr;

  internal Dial(IntPtr cPtr, bool cMemoryOwn) : base(libtischPINVOKE.DialUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Dial obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Dial() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libtischPINVOKE.delete_Dial(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public Dial(int _r, int _x, int _y, double _angle, RGBATexture _tex) : this(libtischPINVOKE.new_Dial__SWIG_0(_r, _x, _y, _angle, libtischPINVOKE.getCPtrAddRef(_tex)), true) {
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  public Dial(int _r, int _x, int _y, double _angle) : this(libtischPINVOKE.new_Dial__SWIG_1(_r, _x, _y, _angle), true) {
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  public Dial(int _r, int _x, int _y) : this(libtischPINVOKE.new_Dial__SWIG_2(_r, _x, _y), true) {
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  public Dial(int _r, int _x) : this(libtischPINVOKE.new_Dial__SWIG_3(_r, _x), true) {
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  public Dial(int _r) : this(libtischPINVOKE.new_Dial__SWIG_4(_r), true) {
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  public override void draw() {
    if (this.GetType() == typeof(Dial)) libtischPINVOKE.Dial_draw(swigCPtr); else libtischPINVOKE.Dial_drawSwigExplicitDial(swigCPtr);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void action(Gesture gesture) {
    if (this.GetType() == typeof(Dial)) libtischPINVOKE.Dial_action(swigCPtr, Gesture.getCPtr(gesture)); else libtischPINVOKE.Dial_actionSwigExplicitDial(swigCPtr, Gesture.getCPtr(gesture));
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void outline() {
    if (this.GetType() == typeof(Dial)) libtischPINVOKE.Dial_outline(swigCPtr); else libtischPINVOKE.Dial_outlineSwigExplicitDial(swigCPtr);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get() {
    double ret = libtischPINVOKE.Dial_get(swigCPtr);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void set(double _angle, double _lower, double _upper) {
    libtischPINVOKE.Dial_set(swigCPtr, _angle, _lower, _upper);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  protected double k_angle {
    set {
      libtischPINVOKE.Dial_k_angle_set(swigCPtr, value);
      if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = libtischPINVOKE.Dial_k_angle_get(swigCPtr);
      if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  protected double k_lower {
    set {
      libtischPINVOKE.Dial_k_lower_set(swigCPtr, value);
      if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = libtischPINVOKE.Dial_k_lower_get(swigCPtr);
      if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  protected double k_upper {
    set {
      libtischPINVOKE.Dial_k_upper_set(swigCPtr, value);
      if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = libtischPINVOKE.Dial_k_upper_get(swigCPtr);
      if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  protected Vector oldpos {
    set {
      libtischPINVOKE.Dial_oldpos_set(swigCPtr, Vector.getCPtr(value));
      if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      IntPtr cPtr = libtischPINVOKE.Dial_oldpos_get(swigCPtr);
      Vector ret = (cPtr == IntPtr.Zero) ? null : new Vector(cPtr, false);
      if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("outline", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateDial_0(SwigDirectoroutline);
    if (SwigDerivedClassHasMethod("update", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateDial_1(SwigDirectorupdate__SWIG_0);
    if (SwigDerivedClassHasMethod("update", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateDial_2(SwigDirectorupdate__SWIG_1);
    if (SwigDerivedClassHasMethod("doUpdate", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateDial_3(SwigDirectordoUpdate__SWIG_0);
    if (SwigDerivedClassHasMethod("doUpdate", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateDial_4(SwigDirectordoUpdate__SWIG_1);
    if (SwigDerivedClassHasMethod("raise", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateDial_5(SwigDirectorraise__SWIG_0);
    if (SwigDerivedClassHasMethod("raise", swigMethodTypes6))
      swigDelegate6 = new SwigDelegateDial_6(SwigDirectorraise__SWIG_1);
    if (SwigDerivedClassHasMethod("lower", swigMethodTypes7))
      swigDelegate7 = new SwigDelegateDial_7(SwigDirectorlower__SWIG_0);
    if (SwigDerivedClassHasMethod("lower", swigMethodTypes8))
      swigDelegate8 = new SwigDelegateDial_8(SwigDirectorlower__SWIG_1);
    if (SwigDerivedClassHasMethod("draw", swigMethodTypes9))
      swigDelegate9 = new SwigDelegateDial_9(SwigDirectordraw);
    if (SwigDerivedClassHasMethod("action", swigMethodTypes10))
      swigDelegate10 = new SwigDelegateDial_10(SwigDirectoraction);
    if (SwigDerivedClassHasMethod("enter", swigMethodTypes11))
      swigDelegate11 = new SwigDelegateDial_11(SwigDirectorenter__SWIG_0);
    if (SwigDerivedClassHasMethod("enter", swigMethodTypes12))
      swigDelegate12 = new SwigDelegateDial_12(SwigDirectorenter__SWIG_1);
    if (SwigDerivedClassHasMethod("paint", swigMethodTypes13))
      swigDelegate13 = new SwigDelegateDial_13(SwigDirectorpaint__SWIG_0);
    if (SwigDerivedClassHasMethod("paint", swigMethodTypes14))
      swigDelegate14 = new SwigDelegateDial_14(SwigDirectorpaint__SWIG_1);
    libtischPINVOKE.Dial_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6, swigDelegate7, swigDelegate8, swigDelegate9, swigDelegate10, swigDelegate11, swigDelegate12, swigDelegate13, swigDelegate14);
  }

  private bool SwigDerivedClassHasMethod(string methodName, Type[] methodTypes) {
    System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(Dial));
    return hasDerivedMethod;
  }

  private void SwigDirectoroutline() {
    outline();
  }

  private void SwigDirectorupdate__SWIG_0(IntPtr target) {
    update((target == IntPtr.Zero) ? null : new Widget(target, false));
  }

  private void SwigDirectorupdate__SWIG_1() {
    update();
  }

  private void SwigDirectordoUpdate__SWIG_0(IntPtr target) {
    doUpdate((target == IntPtr.Zero) ? null : new Widget(target, false));
  }

  private void SwigDirectordoUpdate__SWIG_1() {
    doUpdate();
  }

  private void SwigDirectorraise__SWIG_0(IntPtr widget) {
    raise((widget == IntPtr.Zero) ? null : new Widget(widget, false));
  }

  private void SwigDirectorraise__SWIG_1() {
    raise();
  }

  private void SwigDirectorlower__SWIG_0(IntPtr widget) {
    lower((widget == IntPtr.Zero) ? null : new Widget(widget, false));
  }

  private void SwigDirectorlower__SWIG_1() {
    lower();
  }

  private void SwigDirectordraw() {
    draw();
  }

  private void SwigDirectoraction(IntPtr gesture) {
    action((gesture == IntPtr.Zero) ? null : new Gesture(gesture, false));
  }

  private void SwigDirectorenter__SWIG_0(double z) {
    enter(z);
  }

  private void SwigDirectorenter__SWIG_1() {
    enter();
  }

  private void SwigDirectorpaint__SWIG_0(bool update_stencil) {
    paint(update_stencil);
  }

  private void SwigDirectorpaint__SWIG_1() {
    paint();
  }

  public delegate void SwigDelegateDial_0();
  public delegate void SwigDelegateDial_1(IntPtr target);
  public delegate void SwigDelegateDial_2();
  public delegate void SwigDelegateDial_3(IntPtr target);
  public delegate void SwigDelegateDial_4();
  public delegate void SwigDelegateDial_5(IntPtr widget);
  public delegate void SwigDelegateDial_6();
  public delegate void SwigDelegateDial_7(IntPtr widget);
  public delegate void SwigDelegateDial_8();
  public delegate void SwigDelegateDial_9();
  public delegate void SwigDelegateDial_10(IntPtr gesture);
  public delegate void SwigDelegateDial_11(double z);
  public delegate void SwigDelegateDial_12();
  public delegate void SwigDelegateDial_13(bool update_stencil);
  public delegate void SwigDelegateDial_14();

  private SwigDelegateDial_0 swigDelegate0;
  private SwigDelegateDial_1 swigDelegate1;
  private SwigDelegateDial_2 swigDelegate2;
  private SwigDelegateDial_3 swigDelegate3;
  private SwigDelegateDial_4 swigDelegate4;
  private SwigDelegateDial_5 swigDelegate5;
  private SwigDelegateDial_6 swigDelegate6;
  private SwigDelegateDial_7 swigDelegate7;
  private SwigDelegateDial_8 swigDelegate8;
  private SwigDelegateDial_9 swigDelegate9;
  private SwigDelegateDial_10 swigDelegate10;
  private SwigDelegateDial_11 swigDelegate11;
  private SwigDelegateDial_12 swigDelegate12;
  private SwigDelegateDial_13 swigDelegate13;
  private SwigDelegateDial_14 swigDelegate14;

  private static Type[] swigMethodTypes0 = new Type[] {  };
  private static Type[] swigMethodTypes1 = new Type[] { typeof(Widget) };
  private static Type[] swigMethodTypes2 = new Type[] {  };
  private static Type[] swigMethodTypes3 = new Type[] { typeof(Widget) };
  private static Type[] swigMethodTypes4 = new Type[] {  };
  private static Type[] swigMethodTypes5 = new Type[] { typeof(Widget) };
  private static Type[] swigMethodTypes6 = new Type[] {  };
  private static Type[] swigMethodTypes7 = new Type[] { typeof(Widget) };
  private static Type[] swigMethodTypes8 = new Type[] {  };
  private static Type[] swigMethodTypes9 = new Type[] {  };
  private static Type[] swigMethodTypes10 = new Type[] { typeof(Gesture) };
  private static Type[] swigMethodTypes11 = new Type[] { typeof(double) };
  private static Type[] swigMethodTypes12 = new Type[] {  };
  private static Type[] swigMethodTypes13 = new Type[] { typeof(bool) };
  private static Type[] swigMethodTypes14 = new Type[] {  };
}
