/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum InputType {
  INPUT_TYPE_UNKNOWN,
  INPUT_TYPE_FINGER_RI,
  INPUT_TYPE_FINGER_RM,
  INPUT_TYPE_FINGER_RR,
  INPUT_TYPE_FINGER_RL,
  INPUT_TYPE_FINGER_RT,
  INPUT_TYPE_FINGER_LI,
  INPUT_TYPE_FINGER_LM,
  INPUT_TYPE_FINGER_LR,
  INPUT_TYPE_FINGER_LL,
  INPUT_TYPE_FINGER_LT,
  INPUT_TYPE_STYLUS,
  INPUT_TYPE_LASER,
  INPUT_TYPE_MOUSE,
  INPUT_TYPE_TRACKBALL,
  INPUT_TYPE_JOYSTICK,
  INPUT_TYPE_WIIMOTE,
  INPUT_TYPE_EYETRACKER,
  INPUT_TYPE_OBJECT,
  INPUT_TYPE_TOKEN,
  INPUT_TYPE_HAND_RP = 21,
  INPUT_TYPE_HAND_RO,
  INPUT_TYPE_HAND_RC,
  INPUT_TYPE_HAND_LP,
  INPUT_TYPE_HAND_LO,
  INPUT_TYPE_HAND_LC,
  INPUT_TYPE_FOOT_R,
  INPUT_TYPE_FOOT_L,
  INPUT_TYPE_HEAD,
  INPUT_TYPE_PERSON,
  INPUT_TYPE_COUNT
}
