TOPDIR = ../../

CFLAGS += -I$(TOPDIR)/libs/tools/ -I$(TOPDIR)/libs/osc/ -I$(TOPDIR)
LDFLAGS += -ltools -loscpack -L$(TOPDIR)/libs/tools/ -L$(TOPDIR)/libs/osc/

APPS=evdevd

include $(TOPDIR)/scripts/rules.mk

