/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class BlobState : mapIntBlobHistory {
  private HandleRef swigCPtr;

  internal BlobState(IntPtr cPtr, bool cMemoryOwn) : base(libtischPINVOKE.BlobStateUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(BlobState obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~BlobState() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        libtischPINVOKE.delete_BlobState(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public BlobState() : this(libtischPINVOKE.new_BlobState(), true) {
  }

  public void purge() {
    libtischPINVOKE.BlobState_purge(swigCPtr);
  }

  public vectorInt lost {
    set {
      libtischPINVOKE.BlobState_lost_set(swigCPtr, vectorInt.getCPtr(value));
    } 
    get {
      IntPtr cPtr = libtischPINVOKE.BlobState_lost_get(swigCPtr);
      vectorInt ret = (cPtr == IntPtr.Zero) ? null : new vectorInt(cPtr, false);
      return ret;
    } 
  }

  public int changed {
    set {
      libtischPINVOKE.BlobState_changed_set(swigCPtr, value);
    } 
    get {
      int ret = libtischPINVOKE.BlobState_changed_get(swigCPtr);
      return ret;
    } 
  }

}
