/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class vectorDouble : IDisposable, System.Collections.IEnumerable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vectorDouble(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(vectorDouble obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~vectorDouble() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        libtischPINVOKE.delete_vectorDouble(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public vectorDouble(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (double element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public double this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(System.Array array) {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(System.Array array, int arrayIndex) {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, System.Array array, int arrayIndex, int count) {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  // Type-safe version of IEnumerable.GetEnumerator
  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new vectorDoubleEnumerator(this);
  }

  public vectorDoubleEnumerator GetEnumerator() {
    return new vectorDoubleEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class vectorDoubleEnumerator : System.Collections.IEnumerator {
    private vectorDouble collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public vectorDoubleEnumerator(vectorDouble collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public double Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (double)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }
  }

  public void Clear() {
    libtischPINVOKE.vectorDouble_Clear(swigCPtr);
  }

  public void Add(double x) {
    libtischPINVOKE.vectorDouble_Add(swigCPtr, x);
  }

  private uint size() {
    uint ret = libtischPINVOKE.vectorDouble_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = libtischPINVOKE.vectorDouble_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    libtischPINVOKE.vectorDouble_reserve(swigCPtr, n);
  }

  public vectorDouble() : this(libtischPINVOKE.new_vectorDouble__SWIG_0(), true) {
  }

  public vectorDouble(int capacity) : this(libtischPINVOKE.new_vectorDouble__SWIG_1(capacity), true) {
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  private double getitemcopy(int index) {
    double ret = libtischPINVOKE.vectorDouble_getitemcopy(swigCPtr, index);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private double getitem(int index) {
    double ret = libtischPINVOKE.vectorDouble_getitem(swigCPtr, index);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, double val) {
    libtischPINVOKE.vectorDouble_setitem(swigCPtr, index, val);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(vectorDouble values) {
    libtischPINVOKE.vectorDouble_AddRange(swigCPtr, vectorDouble.getCPtr(values));
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  public vectorDouble GetRange(int index, int count) {
    IntPtr cPtr = libtischPINVOKE.vectorDouble_GetRange(swigCPtr, index, count);
    vectorDouble ret = (cPtr == IntPtr.Zero) ? null : new vectorDouble(cPtr, true);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, double x) {
    libtischPINVOKE.vectorDouble_Insert(swigCPtr, index, x);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, vectorDouble values) {
    libtischPINVOKE.vectorDouble_InsertRange(swigCPtr, index, vectorDouble.getCPtr(values));
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    libtischPINVOKE.vectorDouble_RemoveAt(swigCPtr, index);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    libtischPINVOKE.vectorDouble_RemoveRange(swigCPtr, index, count);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  public static vectorDouble Repeat(double value, int count) {
    IntPtr cPtr = libtischPINVOKE.vectorDouble_Repeat(value, count);
    vectorDouble ret = (cPtr == IntPtr.Zero) ? null : new vectorDouble(cPtr, true);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    libtischPINVOKE.vectorDouble_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    libtischPINVOKE.vectorDouble_Reverse__SWIG_1(swigCPtr, index, count);
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, vectorDouble values) {
    libtischPINVOKE.vectorDouble_SetRange(swigCPtr, index, vectorDouble.getCPtr(values));
    if (libtischPINVOKE.SWIGPendingException.Pending) throw libtischPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(double value) {
    bool ret = libtischPINVOKE.vectorDouble_Contains(swigCPtr, value);
    return ret;
  }

  public int IndexOf(double value) {
    int ret = libtischPINVOKE.vectorDouble_IndexOf(swigCPtr, value);
    return ret;
  }

  public int LastIndexOf(double value) {
    int ret = libtischPINVOKE.vectorDouble_LastIndexOf(swigCPtr, value);
    return ret;
  }

  public void Remove(double value) {
    libtischPINVOKE.vectorDouble_Remove(swigCPtr, value);
  }

}
