/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public final class InputType {
  public final static InputType INPUT_TYPE_FINGER = new InputType("INPUT_TYPE_FINGER");
  public final static InputType INPUT_TYPE_HAND = new InputType("INPUT_TYPE_HAND");
  public final static InputType INPUT_TYPE_SHADOW = new InputType("INPUT_TYPE_SHADOW");
  public final static InputType INPUT_TYPE_OBJECT = new InputType("INPUT_TYPE_OBJECT");
  public final static InputType INPUT_TYPE_OTHER = new InputType("INPUT_TYPE_OTHER");
  public final static InputType INPUT_TYPE_COUNT = new InputType("INPUT_TYPE_COUNT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static InputType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + InputType.class + " with value " + swigValue);
  }

  private InputType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private InputType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private InputType(String swigName, InputType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static InputType[] swigValues = { INPUT_TYPE_FINGER, INPUT_TYPE_HAND, INPUT_TYPE_SHADOW, INPUT_TYPE_OBJECT, INPUT_TYPE_OTHER, INPUT_TYPE_COUNT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

