/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libtisch;

public class MasterContainer extends Container {
  private long swigCPtr;

  protected MasterContainer(long cPtr, boolean cMemoryOwn) {
    super(libtischJNI.SWIGMasterContainerUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MasterContainer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      libtischJNI.delete_MasterContainer(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public MasterContainer(int w, int h, String target) {
    this(libtischJNI.new_MasterContainer__SWIG_0(w, h, target), true);
  }

  public MasterContainer(int w, int h) {
    this(libtischJNI.new_MasterContainer__SWIG_1(w, h), true);
  }

  public int process() {
    return libtischJNI.MasterContainer_process(swigCPtr, this);
  }

  public void update(Widget target) {
    libtischJNI.MasterContainer_update__SWIG_0(swigCPtr, this, Widget.getCPtr(target), target);
  }

  public void update() {
    libtischJNI.MasterContainer_update__SWIG_1(swigCPtr, this);
  }

  public void adjust(int w, int h) {
    libtischJNI.MasterContainer_adjust(swigCPtr, this, w, h);
  }

}
