/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_libtisch_WRAP_H_
#define SWIG_libtisch_WRAP_H_

class SwigDirector_FeatureBase : public FeatureBase, public Swig::Director {

public:
    SwigDirector_FeatureBase(unsigned int _tf = 0);
    virtual ~SwigDirector_FeatureBase();
    virtual char const *name() const;
    virtual FeatureBase *clone() const;
    virtual void load(InputState &state);
    virtual int next();
    virtual void serialize(std::ostream &s);
    virtual void unserialize(std::istream &s);
    using FeatureBase::typeflags;

    typedef char * (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(void *);
    typedef int (SWIGSTDCALL* SWIG_Callback3_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackname, SWIG_Callback1_t callbackclone, SWIG_Callback2_t callbackload, SWIG_Callback3_t callbacknext, SWIG_Callback4_t callbackserialize, SWIG_Callback5_t callbackunserialize);

private:
    SWIG_Callback0_t swig_callbackname;
    SWIG_Callback1_t swig_callbackclone;
    SWIG_Callback2_t swig_callbackload;
    SWIG_Callback3_t swig_callbacknext;
    SWIG_Callback4_t swig_callbackserialize;
    SWIG_Callback5_t swig_callbackunserialize;
    void swig_init_callbacks();
};

class SwigDirector_Widget : public Widget, public Swig::Director {

public:
    SwigDirector_Widget(int _w, int _h, int _x = 0, int _y = 0, double _angle = 0.0, RGBATexture *_tex = 0, unsigned int _regflags = (((unsigned int) 1 << INPUT_TYPE_COUNT) -1));
    virtual ~SwigDirector_Widget();
    virtual void outline();
    virtual void update(Widget *target = 0);
    virtual void doUpdate(Widget *target = 0);
    virtual void raise(Widget *widget = 0);
    virtual void lower(Widget *widget = 0);
    virtual void draw();
    virtual void action(Gesture *gesture);
    virtual void enter(double z = 0.0);
    virtual void paint(bool update_stencil = false);
    using Widget::unregister;
    using Widget::mytex;
    using Widget::mycolor;
    using Widget::parent;
    using Widget::m_model;

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)();
    void swig_connect_director(SWIG_Callback0_t callbackoutline, SWIG_Callback1_t callbackupdate__SWIG_0, SWIG_Callback2_t callbackupdate__SWIG_1, SWIG_Callback3_t callbackdoUpdate__SWIG_0, SWIG_Callback4_t callbackdoUpdate__SWIG_1, SWIG_Callback5_t callbackraise__SWIG_0, SWIG_Callback6_t callbackraise__SWIG_1, SWIG_Callback7_t callbacklower__SWIG_0, SWIG_Callback8_t callbacklower__SWIG_1, SWIG_Callback9_t callbackdraw, SWIG_Callback10_t callbackaction, SWIG_Callback11_t callbackenter__SWIG_0, SWIG_Callback12_t callbackenter__SWIG_1, SWIG_Callback13_t callbackpaint__SWIG_0, SWIG_Callback14_t callbackpaint__SWIG_1);

private:
    SWIG_Callback0_t swig_callbackoutline;
    SWIG_Callback1_t swig_callbackupdate__SWIG_0;
    SWIG_Callback2_t swig_callbackupdate__SWIG_1;
    SWIG_Callback3_t swig_callbackdoUpdate__SWIG_0;
    SWIG_Callback4_t swig_callbackdoUpdate__SWIG_1;
    SWIG_Callback5_t swig_callbackraise__SWIG_0;
    SWIG_Callback6_t swig_callbackraise__SWIG_1;
    SWIG_Callback7_t swig_callbacklower__SWIG_0;
    SWIG_Callback8_t swig_callbacklower__SWIG_1;
    SWIG_Callback9_t swig_callbackdraw;
    SWIG_Callback10_t swig_callbackaction;
    SWIG_Callback11_t swig_callbackenter__SWIG_0;
    SWIG_Callback12_t swig_callbackenter__SWIG_1;
    SWIG_Callback13_t swig_callbackpaint__SWIG_0;
    SWIG_Callback14_t swig_callbackpaint__SWIG_1;
    void swig_init_callbacks();
};

class SwigDirector_Label : public Label, public Swig::Director {

public:
    SwigDirector_Label(char const *text, int _w, int _h, int _x = 0, int _y = 0, double angle = 0.0, int center = 0, int snip = 0, RGBATexture *_tex = 0);
    virtual ~SwigDirector_Label();
    virtual void outline();
    virtual void update(Widget *target = 0);
    virtual void doUpdate(Widget *target = 0);
    virtual void raise(Widget *widget = 0);
    virtual void lower(Widget *widget = 0);
    virtual void draw();
    virtual void action(Gesture *gesture);
    virtual void enter(double z = 0.0);
    virtual void paint(bool update_stencil = false);
    using Label::text;
    using Label::center;
    using Label::snip;

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)();
    void swig_connect_director(SWIG_Callback0_t callbackoutline, SWIG_Callback1_t callbackupdate__SWIG_0, SWIG_Callback2_t callbackupdate__SWIG_1, SWIG_Callback3_t callbackdoUpdate__SWIG_0, SWIG_Callback4_t callbackdoUpdate__SWIG_1, SWIG_Callback5_t callbackraise__SWIG_0, SWIG_Callback6_t callbackraise__SWIG_1, SWIG_Callback7_t callbacklower__SWIG_0, SWIG_Callback8_t callbacklower__SWIG_1, SWIG_Callback9_t callbackdraw, SWIG_Callback10_t callbackaction, SWIG_Callback11_t callbackenter__SWIG_0, SWIG_Callback12_t callbackenter__SWIG_1, SWIG_Callback13_t callbackpaint__SWIG_0, SWIG_Callback14_t callbackpaint__SWIG_1);

private:
    SWIG_Callback0_t swig_callbackoutline;
    SWIG_Callback1_t swig_callbackupdate__SWIG_0;
    SWIG_Callback2_t swig_callbackupdate__SWIG_1;
    SWIG_Callback3_t swig_callbackdoUpdate__SWIG_0;
    SWIG_Callback4_t swig_callbackdoUpdate__SWIG_1;
    SWIG_Callback5_t swig_callbackraise__SWIG_0;
    SWIG_Callback6_t swig_callbackraise__SWIG_1;
    SWIG_Callback7_t swig_callbacklower__SWIG_0;
    SWIG_Callback8_t swig_callbacklower__SWIG_1;
    SWIG_Callback9_t swig_callbackdraw;
    SWIG_Callback10_t swig_callbackaction;
    SWIG_Callback11_t swig_callbackenter__SWIG_0;
    SWIG_Callback12_t swig_callbackenter__SWIG_1;
    SWIG_Callback13_t swig_callbackpaint__SWIG_0;
    SWIG_Callback14_t swig_callbackpaint__SWIG_1;
    void swig_init_callbacks();
};

class SwigDirector_Button : public Button, public Swig::Director {

public:
    SwigDirector_Button(int _w, int _h, int _x = 0, int _y = 0, double angle = 0.0, RGBATexture *_tex = 0);
    virtual ~SwigDirector_Button();
    virtual void outline();
    virtual void update(Widget *target = 0);
    virtual void doUpdate(Widget *target = 0);
    virtual void raise(Widget *widget = 0);
    virtual void lower(Widget *widget = 0);
    virtual void draw();
    virtual void action(Gesture *gesture);
    virtual void enter(double z = 0.0);
    virtual void paint(bool update_stencil = false);
    virtual void tap(Vector pos, int id);
    virtual void release();
    using Button::active;

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(void *, int);
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)();
    void swig_connect_director(SWIG_Callback0_t callbackoutline, SWIG_Callback1_t callbackupdate__SWIG_0, SWIG_Callback2_t callbackupdate__SWIG_1, SWIG_Callback3_t callbackdoUpdate__SWIG_0, SWIG_Callback4_t callbackdoUpdate__SWIG_1, SWIG_Callback5_t callbackraise__SWIG_0, SWIG_Callback6_t callbackraise__SWIG_1, SWIG_Callback7_t callbacklower__SWIG_0, SWIG_Callback8_t callbacklower__SWIG_1, SWIG_Callback9_t callbackdraw, SWIG_Callback10_t callbackaction, SWIG_Callback11_t callbackenter__SWIG_0, SWIG_Callback12_t callbackenter__SWIG_1, SWIG_Callback13_t callbackpaint__SWIG_0, SWIG_Callback14_t callbackpaint__SWIG_1, SWIG_Callback15_t callbacktap, SWIG_Callback16_t callbackrelease);

private:
    SWIG_Callback0_t swig_callbackoutline;
    SWIG_Callback1_t swig_callbackupdate__SWIG_0;
    SWIG_Callback2_t swig_callbackupdate__SWIG_1;
    SWIG_Callback3_t swig_callbackdoUpdate__SWIG_0;
    SWIG_Callback4_t swig_callbackdoUpdate__SWIG_1;
    SWIG_Callback5_t swig_callbackraise__SWIG_0;
    SWIG_Callback6_t swig_callbackraise__SWIG_1;
    SWIG_Callback7_t swig_callbacklower__SWIG_0;
    SWIG_Callback8_t swig_callbacklower__SWIG_1;
    SWIG_Callback9_t swig_callbackdraw;
    SWIG_Callback10_t swig_callbackaction;
    SWIG_Callback11_t swig_callbackenter__SWIG_0;
    SWIG_Callback12_t swig_callbackenter__SWIG_1;
    SWIG_Callback13_t swig_callbackpaint__SWIG_0;
    SWIG_Callback14_t swig_callbackpaint__SWIG_1;
    SWIG_Callback15_t swig_callbacktap;
    SWIG_Callback16_t swig_callbackrelease;
    void swig_init_callbacks();
};

class SwigDirector_Tile : public Tile, public Swig::Director {

public:
    SwigDirector_Tile(int _w, int _h, int _x = 0, int _y = 0, double angle = 0.0, RGBATexture *_tex = 0, int _mode = 0xFF);
    virtual ~SwigDirector_Tile();
    virtual void outline();
    virtual void update(Widget *target = 0);
    virtual void doUpdate(Widget *target = 0);
    virtual void raise(Widget *widget = 0);
    virtual void lower(Widget *widget = 0);
    virtual void draw();
    virtual void action(Gesture *gesture);
    virtual void enter(double z = 0.0);
    virtual void paint(bool update_stencil = false);
    virtual void tap(Vector pos, int id);
    virtual void release();
    virtual void apply(Vector delta);
    using Tile::mode;
    using Tile::slide;
    using Tile::vel;

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(void *, int);
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback17_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackoutline, SWIG_Callback1_t callbackupdate__SWIG_0, SWIG_Callback2_t callbackupdate__SWIG_1, SWIG_Callback3_t callbackdoUpdate__SWIG_0, SWIG_Callback4_t callbackdoUpdate__SWIG_1, SWIG_Callback5_t callbackraise__SWIG_0, SWIG_Callback6_t callbackraise__SWIG_1, SWIG_Callback7_t callbacklower__SWIG_0, SWIG_Callback8_t callbacklower__SWIG_1, SWIG_Callback9_t callbackdraw, SWIG_Callback10_t callbackaction, SWIG_Callback11_t callbackenter__SWIG_0, SWIG_Callback12_t callbackenter__SWIG_1, SWIG_Callback13_t callbackpaint__SWIG_0, SWIG_Callback14_t callbackpaint__SWIG_1, SWIG_Callback15_t callbacktap, SWIG_Callback16_t callbackrelease, SWIG_Callback17_t callbackapply);

private:
    SWIG_Callback0_t swig_callbackoutline;
    SWIG_Callback1_t swig_callbackupdate__SWIG_0;
    SWIG_Callback2_t swig_callbackupdate__SWIG_1;
    SWIG_Callback3_t swig_callbackdoUpdate__SWIG_0;
    SWIG_Callback4_t swig_callbackdoUpdate__SWIG_1;
    SWIG_Callback5_t swig_callbackraise__SWIG_0;
    SWIG_Callback6_t swig_callbackraise__SWIG_1;
    SWIG_Callback7_t swig_callbacklower__SWIG_0;
    SWIG_Callback8_t swig_callbacklower__SWIG_1;
    SWIG_Callback9_t swig_callbackdraw;
    SWIG_Callback10_t swig_callbackaction;
    SWIG_Callback11_t swig_callbackenter__SWIG_0;
    SWIG_Callback12_t swig_callbackenter__SWIG_1;
    SWIG_Callback13_t swig_callbackpaint__SWIG_0;
    SWIG_Callback14_t swig_callbackpaint__SWIG_1;
    SWIG_Callback15_t swig_callbacktap;
    SWIG_Callback16_t swig_callbackrelease;
    SWIG_Callback17_t swig_callbackapply;
    void swig_init_callbacks();
};

class SwigDirector_Container : public Container, public Swig::Director {

public:
    SwigDirector_Container(int w, int h, int x, int y, double angle = 0.0, RGBATexture *tex = 0, int mode = 32);
    virtual ~SwigDirector_Container();
    virtual void outline();
    virtual void update(Widget *target = 0);
    virtual void doUpdate(Widget *target = 0);
    virtual void raise(Widget *widget = 0);
    virtual void lower(Widget *widget = 0);
    virtual void draw();
    virtual void action(Gesture *gesture);
    virtual void enter(double z = 0.0);
    virtual void paint(bool update_stencil = false);
    virtual void tap(Vector vec, int id);
    virtual void release();
    virtual void apply(Vector delta);
    using Container::totalHeight;
    using Container::widgets;
    using Container::locked;

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(void *, int);
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback17_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackoutline, SWIG_Callback1_t callbackupdate__SWIG_0, SWIG_Callback2_t callbackupdate__SWIG_1, SWIG_Callback3_t callbackdoUpdate__SWIG_0, SWIG_Callback4_t callbackdoUpdate__SWIG_1, SWIG_Callback5_t callbackraise__SWIG_0, SWIG_Callback6_t callbackraise__SWIG_1, SWIG_Callback7_t callbacklower__SWIG_0, SWIG_Callback8_t callbacklower__SWIG_1, SWIG_Callback9_t callbackdraw, SWIG_Callback10_t callbackaction, SWIG_Callback11_t callbackenter__SWIG_0, SWIG_Callback12_t callbackenter__SWIG_1, SWIG_Callback13_t callbackpaint__SWIG_0, SWIG_Callback14_t callbackpaint__SWIG_1, SWIG_Callback15_t callbacktap, SWIG_Callback16_t callbackrelease, SWIG_Callback17_t callbackapply);

private:
    SWIG_Callback0_t swig_callbackoutline;
    SWIG_Callback1_t swig_callbackupdate__SWIG_0;
    SWIG_Callback2_t swig_callbackupdate__SWIG_1;
    SWIG_Callback3_t swig_callbackdoUpdate__SWIG_0;
    SWIG_Callback4_t swig_callbackdoUpdate__SWIG_1;
    SWIG_Callback5_t swig_callbackraise__SWIG_0;
    SWIG_Callback6_t swig_callbackraise__SWIG_1;
    SWIG_Callback7_t swig_callbacklower__SWIG_0;
    SWIG_Callback8_t swig_callbacklower__SWIG_1;
    SWIG_Callback9_t swig_callbackdraw;
    SWIG_Callback10_t swig_callbackaction;
    SWIG_Callback11_t swig_callbackenter__SWIG_0;
    SWIG_Callback12_t swig_callbackenter__SWIG_1;
    SWIG_Callback13_t swig_callbackpaint__SWIG_0;
    SWIG_Callback14_t swig_callbackpaint__SWIG_1;
    SWIG_Callback15_t swig_callbacktap;
    SWIG_Callback16_t swig_callbackrelease;
    SWIG_Callback17_t swig_callbackapply;
    void swig_init_callbacks();
};

class SwigDirector_Slider : public Slider, public Swig::Director {

public:
    SwigDirector_Slider(int _w, int _h, int _x = 0, int _y = 0, double angle = 0.0, RGBATexture *_tex = 0);
    virtual ~SwigDirector_Slider();
    virtual void outline();
    virtual void update(Widget *target = 0);
    virtual void doUpdate(Widget *target = 0);
    virtual void raise(Widget *widget = 0);
    virtual void lower(Widget *widget = 0);
    virtual void draw();
    virtual void action(Gesture *gesture);
    virtual void enter(double z = 0.0);
    virtual void paint(bool update_stencil = false);
    using Slider::pos;

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)();
    void swig_connect_director(SWIG_Callback0_t callbackoutline, SWIG_Callback1_t callbackupdate__SWIG_0, SWIG_Callback2_t callbackupdate__SWIG_1, SWIG_Callback3_t callbackdoUpdate__SWIG_0, SWIG_Callback4_t callbackdoUpdate__SWIG_1, SWIG_Callback5_t callbackraise__SWIG_0, SWIG_Callback6_t callbackraise__SWIG_1, SWIG_Callback7_t callbacklower__SWIG_0, SWIG_Callback8_t callbacklower__SWIG_1, SWIG_Callback9_t callbackdraw, SWIG_Callback10_t callbackaction, SWIG_Callback11_t callbackenter__SWIG_0, SWIG_Callback12_t callbackenter__SWIG_1, SWIG_Callback13_t callbackpaint__SWIG_0, SWIG_Callback14_t callbackpaint__SWIG_1);

private:
    SWIG_Callback0_t swig_callbackoutline;
    SWIG_Callback1_t swig_callbackupdate__SWIG_0;
    SWIG_Callback2_t swig_callbackupdate__SWIG_1;
    SWIG_Callback3_t swig_callbackdoUpdate__SWIG_0;
    SWIG_Callback4_t swig_callbackdoUpdate__SWIG_1;
    SWIG_Callback5_t swig_callbackraise__SWIG_0;
    SWIG_Callback6_t swig_callbackraise__SWIG_1;
    SWIG_Callback7_t swig_callbacklower__SWIG_0;
    SWIG_Callback8_t swig_callbacklower__SWIG_1;
    SWIG_Callback9_t swig_callbackdraw;
    SWIG_Callback10_t swig_callbackaction;
    SWIG_Callback11_t swig_callbackenter__SWIG_0;
    SWIG_Callback12_t swig_callbackenter__SWIG_1;
    SWIG_Callback13_t swig_callbackpaint__SWIG_0;
    SWIG_Callback14_t swig_callbackpaint__SWIG_1;
    void swig_init_callbacks();
};

class SwigDirector_Dial : public Dial, public Swig::Director {

public:
    SwigDirector_Dial(int _r, int _x = 0, int _y = 0, double _angle = 0.0, RGBATexture *_tex = 0);
    virtual ~SwigDirector_Dial();
    virtual void outline();
    virtual void update(Widget *target = 0);
    virtual void doUpdate(Widget *target = 0);
    virtual void raise(Widget *widget = 0);
    virtual void lower(Widget *widget = 0);
    virtual void draw();
    virtual void action(Gesture *gesture);
    virtual void enter(double z = 0.0);
    virtual void paint(bool update_stencil = false);
    using Dial::k_angle;
    using Dial::k_lower;
    using Dial::k_upper;
    using Dial::oldpos;

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)();
    void swig_connect_director(SWIG_Callback0_t callbackoutline, SWIG_Callback1_t callbackupdate__SWIG_0, SWIG_Callback2_t callbackupdate__SWIG_1, SWIG_Callback3_t callbackdoUpdate__SWIG_0, SWIG_Callback4_t callbackdoUpdate__SWIG_1, SWIG_Callback5_t callbackraise__SWIG_0, SWIG_Callback6_t callbackraise__SWIG_1, SWIG_Callback7_t callbacklower__SWIG_0, SWIG_Callback8_t callbacklower__SWIG_1, SWIG_Callback9_t callbackdraw, SWIG_Callback10_t callbackaction, SWIG_Callback11_t callbackenter__SWIG_0, SWIG_Callback12_t callbackenter__SWIG_1, SWIG_Callback13_t callbackpaint__SWIG_0, SWIG_Callback14_t callbackpaint__SWIG_1);

private:
    SWIG_Callback0_t swig_callbackoutline;
    SWIG_Callback1_t swig_callbackupdate__SWIG_0;
    SWIG_Callback2_t swig_callbackupdate__SWIG_1;
    SWIG_Callback3_t swig_callbackdoUpdate__SWIG_0;
    SWIG_Callback4_t swig_callbackdoUpdate__SWIG_1;
    SWIG_Callback5_t swig_callbackraise__SWIG_0;
    SWIG_Callback6_t swig_callbackraise__SWIG_1;
    SWIG_Callback7_t swig_callbacklower__SWIG_0;
    SWIG_Callback8_t swig_callbacklower__SWIG_1;
    SWIG_Callback9_t swig_callbackdraw;
    SWIG_Callback10_t swig_callbackaction;
    SWIG_Callback11_t swig_callbackenter__SWIG_0;
    SWIG_Callback12_t swig_callbackenter__SWIG_1;
    SWIG_Callback13_t swig_callbackpaint__SWIG_0;
    SWIG_Callback14_t swig_callbackpaint__SWIG_1;
    void swig_init_callbacks();
};

class SwigDirector_MasterContainer : public MasterContainer, public Swig::Director {

public:
    SwigDirector_MasterContainer(int w, int h, int defaults = 1);
    virtual ~SwigDirector_MasterContainer();
    virtual void outline();
    virtual void update(Widget *target = 0);
    virtual void doUpdate(Widget *target = 0);
    virtual void raise(Widget *widget = 0);
    virtual void lower(Widget *widget = 0);
    virtual void draw();
    virtual void action(Gesture *gesture);
    virtual void enter(double z = 0.0);
    virtual void paint(bool update_stencil = false);
    virtual void tap(Vector vec, int id);
    virtual void release();
    virtual void apply(Vector delta);
    using MasterContainer::matcher;
    using MasterContainer::input;
    using MasterContainer::inthread;

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(void *, int);
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback17_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackoutline, SWIG_Callback1_t callbackupdate__SWIG_0, SWIG_Callback2_t callbackupdate__SWIG_1, SWIG_Callback3_t callbackdoUpdate__SWIG_0, SWIG_Callback4_t callbackdoUpdate__SWIG_1, SWIG_Callback5_t callbackraise__SWIG_0, SWIG_Callback6_t callbackraise__SWIG_1, SWIG_Callback7_t callbacklower__SWIG_0, SWIG_Callback8_t callbacklower__SWIG_1, SWIG_Callback9_t callbackdraw, SWIG_Callback10_t callbackaction, SWIG_Callback11_t callbackenter__SWIG_0, SWIG_Callback12_t callbackenter__SWIG_1, SWIG_Callback13_t callbackpaint__SWIG_0, SWIG_Callback14_t callbackpaint__SWIG_1, SWIG_Callback15_t callbacktap, SWIG_Callback16_t callbackrelease, SWIG_Callback17_t callbackapply);

private:
    SWIG_Callback0_t swig_callbackoutline;
    SWIG_Callback1_t swig_callbackupdate__SWIG_0;
    SWIG_Callback2_t swig_callbackupdate__SWIG_1;
    SWIG_Callback3_t swig_callbackdoUpdate__SWIG_0;
    SWIG_Callback4_t swig_callbackdoUpdate__SWIG_1;
    SWIG_Callback5_t swig_callbackraise__SWIG_0;
    SWIG_Callback6_t swig_callbackraise__SWIG_1;
    SWIG_Callback7_t swig_callbacklower__SWIG_0;
    SWIG_Callback8_t swig_callbacklower__SWIG_1;
    SWIG_Callback9_t swig_callbackdraw;
    SWIG_Callback10_t swig_callbackaction;
    SWIG_Callback11_t swig_callbackenter__SWIG_0;
    SWIG_Callback12_t swig_callbackenter__SWIG_1;
    SWIG_Callback13_t swig_callbackpaint__SWIG_0;
    SWIG_Callback14_t swig_callbackpaint__SWIG_1;
    SWIG_Callback15_t swig_callbacktap;
    SWIG_Callback16_t swig_callbackrelease;
    SWIG_Callback17_t swig_callbackapply;
    void swig_init_callbacks();
};

class SwigDirector_Window : public Window, public Swig::Director {

public:
    SwigDirector_Window(int w, int h, std::string title, int use_mouse = 0);
    virtual ~SwigDirector_Window();
    virtual void idle();
    virtual void display();
    virtual void reshape(int w, int h);
    virtual void keyboard(int key, int x, int y);
    virtual void mouse(int num, int button, int state, int x, int y);
    virtual void passive(int num, int x, int y);
    virtual void motion(int num, int x, int y);
    virtual void entry(int num, int state);
    virtual void update(Widget *target = 0);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(int, int);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(int, int, int);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(int, int, int, int, int);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(int, int, int);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(int, int, int);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(int, int);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    void swig_connect_director(SWIG_Callback0_t callbackidle, SWIG_Callback1_t callbackdisplay, SWIG_Callback2_t callbackreshape, SWIG_Callback3_t callbackkeyboard, SWIG_Callback4_t callbackmouse, SWIG_Callback5_t callbackpassive, SWIG_Callback6_t callbackmotion, SWIG_Callback7_t callbackentry, SWIG_Callback8_t callbackupdate__SWIG_0, SWIG_Callback9_t callbackupdate__SWIG_1);

private:
    SWIG_Callback0_t swig_callbackidle;
    SWIG_Callback1_t swig_callbackdisplay;
    SWIG_Callback2_t swig_callbackreshape;
    SWIG_Callback3_t swig_callbackkeyboard;
    SWIG_Callback4_t swig_callbackmouse;
    SWIG_Callback5_t swig_callbackpassive;
    SWIG_Callback6_t swig_callbackmotion;
    SWIG_Callback7_t swig_callbackentry;
    SWIG_Callback8_t swig_callbackupdate__SWIG_0;
    SWIG_Callback9_t swig_callbackupdate__SWIG_1;
    void swig_init_callbacks();
};


#endif
