macmtd: macmtd.mm output.mm
	g++ $^ -o $@ -I ../../ -I ../../libs/osc/ -I ../../libs/tools/ -L../../build/lib -loscpack -ltools -F/System/Library/PrivateFrameworks -framework MultitouchSupport -lIOKit -framework CoreFoundation -framework ApplicationServices -framework AppKit -lobjc 
