TischDemo.exe:
	gmcs -reference:/usr/lib64/mono/gac/Tao.OpenGl/2.1.0.12__1ca010269a4501ef/Tao.OpenGl.dll -reference:/usr/lib64/mono/gac/Tao.FreeGlut/2.4.0.2__6e602a6ad6c0d06d/Tao.FreeGlut.dll -reference:libtisch.dll -out:TischDemo.exe *.cs
